---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Network:
    - Technitium-01:
        href: https://dns-01.darksaber.fyi
        widget:
            type: technitium
            url: https://dns-01.darksaber.fyi
            key: {{HOMEPAGE_VAR_TECHNITIUM_01_KEY}}
            range: LastDay
        

- ARR:
    - Prowlarr:
        href: https://prowlarr.darksaber.fyi
        widget:
            type: prowlarr
            url: https://prowlarr.darksaber.fyi
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}


- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is ðŸ˜Ž
